echo ">>> Criando estrutura de pastas..."
mkdir -p data output notebooks

echo ""
echo "  1. TEMPERATURA (Berkeley Earth):"
echo "     https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data"
echo "     Arquivo: GlobalLandTemperaturesByCity.csv"
echo "     Salve em: ./data/GlobalLandTemperaturesByCity.csv"
echo ""
echo "  2. EMISSÕES CO2 (Our World in Data):"
echo "     https://github.com/owid/co2-data"
echo "     Arquivo: owid-co2-data.csv"
echo "     Salve em: ./data/owid-co2-data.csv"
echo ""
echo "============================================================"
echo ""
echo ">>> Para subir o cluster:"
echo "    docker-compose up -d"
echo ""
echo ">>> Acesse o Jupyter Lab em:"
echo "    http://localhost:8888"
echo ""
echo ">>> Acesse o Spark Master UI em:"
echo "    http://localhost:8080"
echo ""
